version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    kube:
      patterns:
      - kube
      - k8s-openapi
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
